# 不要修改该文件, 会自动生成, 详见 http://gitlab.alibaba-inc.com/node/ci

before_script:
  - '[ ! -d $HOME/.nvm ] && git clone http://gitlab.alibaba-inc.com/node/nvm.git $HOME/.nvm'
  - cd $HOME/.nvm && git pull -p && cd -
  - source $HOME/.nvm/nvm.sh
  - nvm i 4 && nvm alias default 4

node-4:
  script:
    - npm i tnpm@4 --registry=http://registry.npm.alibaba-inc.com
    - node_modules/.bin/tnpm i --install-node=4
    - node_modules/.bin/tnpm run ci
node-6:
  script:
    - npm i tnpm@4 --registry=http://registry.npm.alibaba-inc.com
    - node_modules/.bin/tnpm i --install-node=6
    - node_modules/.bin/tnpm run ci
